name: Hi
on:
  workflow_dispatch:

jobs:
  inspect-env:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v4

      - name: Inspect env
        run: printenv | sort

      - name: Test path
        run: |
          pwd
          ls -al
